In [1]:
import pandas as pd

In [2]:
#read the csv files in
airport = "Resources/airports.csv"

#create df for airports
airport_df = pd.read_csv(airport)

In [3]:
#view the data
airport_df.head()

,id,ident,type,name,latitude_deg,longitude_deg,elevation_ft,continent,iso_country,iso_region,municipality,scheduled_service,gps_code,iata_code,local_code,home_link,wikipedia_link,keywords
0,6523,00A,heliport,Total Rf Heliport,40.070801,-74.933601,11.0,NaN,US,US-PA,Bensalem,no,00A,NaN,00A,NaN,NaN,NaN
1,323361,00AA,small_airport,Aero B Ranch Airport,38.704022,-101.473911,3435.0,NaN,US,US-KS,Leoti,no,00AA,NaN,00AA,NaN,NaN,NaN
2,6524,00AK,small_airport,Lowell Field,59.949200,-151.695999,450.0,NaN,US,US-AK,Anchor Point,no,00AK,NaN,00AK,NaN,NaN,NaN
3,6525,00AL,small_airport,Epps Airpark,34.864799,-86.770302,820.0,NaN,US,US-AL,Harvest,no,00AL,NaN,00AL,NaN,NaN,NaN
4,6526,00AR,closed,Newport Hospital & Clinic Heliport,35.608700,-91.254898,237.0,NaN,US,US-AR,Newport,no,NaN,NaN,NaN,NaN,NaN,00AR

In [4]:
# Locating Airports in the US that have Small Airports
sm_arprts = airport_df.loc[(airport_df['iso_country']=='US') & (airport_df['type']=='small_airport') & (airport_df['iso_region']=='US-NY')]
                                                                
# Dropping NaN in IATA                                                              
sm_arprts = sm_arprts.dropna(subset=['iata_code'])

In [8]:
# Locating Airports in the US that have Medium Airports
md_arprts = airport_df.loc[(airport_df['iso_country']=='US') & (airport_df['type']=='medium_airport') & (airport_df['iso_region']=='US-NY')]
                                                                
# Dropping NaN in IATA                                                              
md_arprts = md_arprts.dropna(subset=['iata_code'])

In [9]:
# Locating Airports in the US that have Medium Airports
lg_arprts = airport_df.loc[(airport_df['iso_country']=='US') & (airport_df['type']=='large_airport') & (airport_df['iso_region']=='US-NY')]
                                                                
# Dropping NaN in IATA                                                              
lg_arprts = lg_arprts.dropna(subset=['iata_code'])

In [10]:
# Creating CSV File
sm_arprts.to_csv('Resources/sm_arprts.csv')
md_arprts.to_csv('Resources/md_arprts.csv')
lg_arprts.to_csv('Resources/lg_arprts.csv')